name: JVM and OS matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'

jobs:
  build:
    concurrency:
      group: pull_request-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.java-version }}
      cancel-in-progress: true
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [ 17, 21, 22 ] #Latest two LTS + latest non-LTS.
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'temurin'
          cache: 'maven'

      # Need to install all Python versions in the same run for tox
      - name: Python 3.10, Python 3.11, Python 3.12 Setup
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.10
            3.11
            3.12
          cache: 'pip'
          cache-dependency-path: |
            **/setup.py

      - name: Install tox
        run:
          pip install tox build

      - name: Build and test timefold-solver
        run: mvn -B -Dfull verify

      - name: Run tox on timefold solver python test suite
        run: python -m tox

      - name: Run tox on jpyinterpreter test suite
        working-directory: ./python/jpyinterpreter
        run: python -m tox
